import type { InternshipApplication } from './types';

export const DEMO_APPLICATIONS: InternshipApplication[] = [
  {
    id: 'demo-01',
    company: '星河出行（演示）',
    role: '线上销售数据分析实习生',
    direction: '数据分析',
    city: '上海',
    source: '公司官网',
    resumeVersion: '经营分析版 V2',
    status: '面试',
    appliedAt: '2026-08-19',
    responseAt: '2026-08-22',
    followUpAt: '2026-09-09',
    jdUrl: '',
    requirements: [
      { id: 'demo-01-r1', requirement: '熟练使用 SQL 和 Python', evidence: 'Olist 项目完成多表建模与 pandas 独立复算', status: '有证据' },
      { id: 'demo-01-r2', requirement: '能够搭建经营指标体系', evidence: '可信经营分析工作台展示指标口径与证据链', status: '有证据' },
      { id: 'demo-01-r3', requirement: '有汽车行业分析经验', evidence: '现有项目为电商场景，需要补充行业理解', status: '需补强' },
    ],
    evidenceCoverage: 83,
    notes: '准备讲清楚指标口径、同期比较和结论边界。',
    createdAt: '2026-08-19T09:00:00.000Z',
    updatedAt: '2026-09-06T09:00:00.000Z',
  },
  {
    id: 'demo-02',
    company: '远帆电商（演示）',
    role: '商业分析实习生',
    direction: '商业分析',
    city: '杭州',
    source: '内推',
    resumeVersion: '经营分析版 V2',
    status: '笔试',
    appliedAt: '2026-08-24',
    responseAt: '2026-08-27',
    followUpAt: '2026-09-10',
    jdUrl: '',
    requirements: [
      { id: 'demo-02-r1', requirement: 'SQL 数据提取与分析', evidence: 'Olist 项目包含 MySQL 数据模型与验证查询', status: '有证据' },
      { id: 'demo-02-r2', requirement: '独立完成业务复盘', evidence: '已有经营分析结论，但真实业务落地证据不足', status: '需补强' },
    ],
    evidenceCoverage: 75,
    notes: '补充 SQL 窗口函数和业务拆解题。',
    createdAt: '2026-08-24T08:00:00.000Z',
    updatedAt: '2026-09-05T08:00:00.000Z',
  },
  {
    id: 'demo-03',
    company: '青屿内容（演示）',
    role: '产品数据分析实习生',
    direction: '产品分析',
    city: '北京',
    source: '牛客',
    resumeVersion: '数据分析版 V1',
    status: '已拒绝',
    appliedAt: '2026-08-15',
    responseAt: '2026-08-20',
    followUpAt: '',
    jdUrl: '',
    requirements: [
      { id: 'demo-03-r1', requirement: '熟悉产品指标和用户行为分析', evidence: '目前主要是经营与履约分析案例', status: '需补强' },
      { id: 'demo-03-r2', requirement: '具备 A/B 实验分析经验', evidence: '', status: '无证据' },
    ],
    evidenceCoverage: 25,
    notes: '缺少互联网产品指标和实验设计案例。',
    createdAt: '2026-08-15T09:30:00.000Z',
    updatedAt: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'demo-04',
    company: '云杉零售（演示）',
    role: '用户增长分析实习生',
    direction: '产品分析',
    city: '深圳',
    source: 'BOSS直聘',
    resumeVersion: '数据分析版 V1',
    status: '已投递',
    appliedAt: '2026-09-01',
    responseAt: '',
    followUpAt: '2026-09-07',
    jdUrl: '',
    requirements: [
      { id: 'demo-04-r1', requirement: '增长漏斗分析', evidence: '具备转化指标拆解思路，缺少真实增长实验', status: '需补强' },
      { id: 'demo-04-r2', requirement: 'SQL 与可视化能力', evidence: 'MySQL、Power BI 与前端仪表板项目', status: '有证据' },
    ],
    evidenceCoverage: 75,
    notes: '需要确认岗位是否接受远程面试。',
    createdAt: '2026-09-01T07:00:00.000Z',
    updatedAt: '2026-09-01T07:00:00.000Z',
  },
  {
    id: 'demo-05',
    company: '北辰汽车（演示）',
    role: '经营分析实习生',
    direction: '商业分析',
    city: '上海',
    source: '实习僧',
    resumeVersion: '经营分析版 V2',
    status: 'Offer',
    appliedAt: '2026-08-08',
    responseAt: '2026-08-10',
    followUpAt: '',
    jdUrl: '',
    requirements: [
      { id: 'demo-05-r1', requirement: '经营数据分析与业务洞察', evidence: 'Olist 经营分析项目与 Power BI 仪表板', status: '有证据' },
      { id: 'demo-05-r2', requirement: '跨部门沟通与落地', evidence: '缺少真实企业协作案例', status: '需补强' },
    ],
    evidenceCoverage: 75,
    notes: '演示数据，不代表真实录用结果。',
    createdAt: '2026-08-08T08:00:00.000Z',
    updatedAt: '2026-08-30T08:00:00.000Z',
  },
  {
    id: 'demo-06',
    company: '木棉科技（演示）',
    role: '数据运营实习生',
    direction: '数据分析',
    city: '广州',
    source: 'BOSS直聘',
    resumeVersion: '数据分析版 V1',
    status: '已投递',
    appliedAt: '2026-09-04',
    responseAt: '',
    followUpAt: '2026-09-11',
    jdUrl: '',
    requirements: [
      { id: 'demo-06-r1', requirement: '活动数据复盘', evidence: '现有项目暂无活动运营场景', status: '无证据' },
      { id: 'demo-06-r2', requirement: '数据清洗和看板制作', evidence: 'Python 数据清洗与 Power BI 看板', status: '有证据' },
    ],
    evidenceCoverage: 50,
    notes: '待补充活动复盘相关案例。',
    createdAt: '2026-09-04T11:00:00.000Z',
    updatedAt: '2026-09-04T11:00:00.000Z',
  },
  {
    id: 'demo-07',
    company: '知微教育（演示）',
    role: 'BI 数据分析实习生',
    direction: '数据分析',
    city: '武汉',
    source: '公司官网',
    resumeVersion: '经营分析版 V2',
    status: '准备投递',
    appliedAt: '2026-09-08',
    responseAt: '',
    followUpAt: '2026-09-14',
    jdUrl: '',
    requirements: [
      { id: 'demo-07-r1', requirement: 'Power BI 报表开发', evidence: 'Olist Power BI 交互式仪表板', status: '有证据' },
      { id: 'demo-07-r2', requirement: '指标口径管理', evidence: '指标定义体检器与可信分析工作台', status: '有证据' },
    ],
    evidenceCoverage: 100,
    notes: '投递前检查 Power BI 项目链接。',
    createdAt: '2026-09-08T06:00:00.000Z',
    updatedAt: '2026-09-08T06:00:00.000Z',
  },
  {
    id: 'demo-08',
    company: '潮汐生活（演示）',
    role: '数据产品实习生',
    direction: '数据产品',
    city: '北京',
    source: '牛客',
    resumeVersion: '产品分析版 V1',
    status: '已投递',
    appliedAt: '2026-09-03',
    responseAt: '2026-09-08',
    followUpAt: '2026-09-12',
    jdUrl: '',
    requirements: [
      { id: 'demo-08-r1', requirement: '数据产品原型设计', evidence: '可信分析助手产品原型', status: '有证据' },
      { id: 'demo-08-r2', requirement: '需求调研与用户验证', evidence: '已设计用户测试，但尚未完成真实用户验证', status: '需补强' },
    ],
    evidenceCoverage: 75,
    notes: '已收到 HR 信息，等待确认面试时间。',
    createdAt: '2026-09-03T06:00:00.000Z',
    updatedAt: '2026-09-08T05:00:00.000Z',
  },
];
